### ISSUE TITLE
Use rem or other values

### ISSUE THREAD

**Issue by circlecube** [mike-diamond/media-query-splitting-plugin#11]
It doesn't look like there is support for using different units as `px` is hard coded. Any thoughts to support this? 

Either a new setting would be ideal where we can set the desired value. Allowing a setting to be set and then use that as the units of measurement throughout the plugin test strings. Something like:
```
new MediaQuerySplittingPlugin({
  units: 'px' (default), // 'rem', etc
})
```

Or allowing the unit measurement to be included in the provided values and update the search strings to not append the px if `inlineUnits` is set. Something like:
```
new MediaQuerySplittingPlugin({
  media: {
    mobileEnd: '30rem',
    tabletEnd: '60rem',
  },
  inlineUnits: true,
})
```

Thanks for the plugin, it's been helpful so far but could be more flexible with these updates!

**Comment by stevenmusumeche** [comment]
@mike-diamond would you be interested in this feature? I'm happy to do the work and make a PR.

**Comment by ScriptedAlchemy** [comment]
@mike-diamond seconding that, and emailing you. Will you take a pull request if we put one forward. I'd much rather contribute than fork OSS projects

**Comment by mike-diamond** [comment]
@ScriptedAlchemy, yes you are welcome to make pr

**Comment by mike-diamond** [comment]
Hi guys, I have just added `units` parameter to the plugin config in v. 1.1.14 release.
Please check out how it works for you

**Comment by circlecube** [comment]
Thanks, @mike-diamond 

The update looks good, but when I try the new version the build fails. 

Reported here: #12

**Comment by stevenmusumeche** [comment]
@mike-diamond I am still working on my PR, but I wanted to point out that your new implementation won't work for rems due to the math for calculating the breakpoints.  Adding/subtracting 1 works for pixels but not for rems.  I should have my PR up soon.
