### ISSUE TITLE
TypeError: MediaQuerySplittingPlugin is not a constructor

### ISSUE THREAD

**Issue by circlecube** [mike-diamond/media-query-splitting-plugin#12]
With the latest update `1.1.14` builds in two projects fail with this error.

`TypeError: MediaQuerySplittingPlugin is not a constructor`

Version `1.1.13` however has no error.

**Comment by mike-diamond** [comment]
Ok, thank you I'll check

**Comment by mike-diamond** [comment]
@circlecube please check v 1.1.16
It should fix the problem

**Comment by Josecc** [comment]
that fixed the problem for me, thanks!

**Comment by circlecube** [comment]
Thank you, that fixes it for me too.
