### ISSUE TITLE
Make changes to a media will change hash of all other ones !

### ISSUE THREAD

**Issue by dNitro** [mike-diamond/media-query-splitting-plugin#14]
When making a change to a media ( for example the desktop one), this plugin changes all other media hashes too.
This is harmful to long term caching as all users ( include mobile ones ) now need to make a request to receive the new styles while nothing has changed. This should happen only to desktop users.

So when we make a change to a media, only the hash of this chunk should change and others should remain untouched as their content does not change at all.

**Comment by mike-diamond** [comment]
Will fix in the next release

**Comment by mike-diamond** [comment]
Fixed in version 2.0.4
