### ISSUE TITLE
Unminified source code

### ISSUE THREAD

**Issue by erichstark** [mike-diamond/media-query-splitting-plugin#17]
Hey Mike,

could you please push unminified source code?

I would like to add groups or range, for example if you have multiple breakpoints for mobile or when you do mobile first approach.

For example:
`
media: {
    mobileEnd: 767,
    tabletStart: 768,
    tabletEnd: 991
    desktopStart: 992
  },
  range: true
`
Where **range** means for tablet, that any media query between **tabletStart** and **tabletEnd** would be targeted.

What do you think?

**Comment by mike-diamond** [comment]
Implemented in v 2.0.0, you can define your own media query instead of breakpoints
