### ISSUE TITLE
Duplicated directives on tablet

### ISSUE THREAD

**Issue by ryssbowh** [mike-diamond/media-query-splitting-plugin#18]
Hi,

First of all thanks for this very useful package, got a little issue I think,
I can see some queries outputed twice in the tablet.css. example source.scss :
```
p {
  margin: 1rem;
}

@media all and (min-width: 569px) { 
  p {
    margin: 2rem;
  }
}
```
desktop.css looks as expected with one directive in it but here's the result of tablet.css :
```
@media all and (min-width: 569px) {
  p {
    margin: 2rem;
  }

  p {
    margin: 2rem;
  }
}
```
I turned off the splitTablet option for this example. If I turn it on, tablet.css is still duplicated, but both landscape and portrait are correct.
I'm using version 1.1.17 and the boilerplate you provided on the example.

Thanks !

**Comment by mike-diamond** [comment]
Please try v 2.0.0 all the split logic reworked there
