### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by tingc10** [mike-diamond/media-query-splitting-plugin#2]
I believe the offending line is https://github.com/mike-diamond/media-query-splitting-plugin/blob/bbe8e1198cd3c2a8ae374e70fe982e49b622a0ef/dist/index.js#L199.

Never worked on a Webpack Plugin before, but I think you need to use `compiler.hooks.emit.tap(pluginName, ...`?

I'm on Webpack 4 btw.

**Comment by mike-diamond** [comment]
This will be fixed with the new major version
