### ISSUE TITLE
No chunk loading found! Use mini-css-extract-plugin v0.4.3 to handle this error

### ISSUE THREAD

**Issue by tingc10** [mike-diamond/media-query-splitting-plugin#3]
I ran into this error and followed the advice, but it didn't resolve the problem. I cloned the repo and realized that the reason was because the `source` parameter is an empty string when processing my `manifest` runtime chunk. This part coincides with generating my `manifest.js` runtime code and the Error causes my chunk to not be created. Is there an alternative way of checking if it is using `mini-css-extract-plugin`? For what it's worth, the media queries are being split out. Currently, I forked your repo and simply removed the Error, my code works fine in the meantime.

**Comment by mike-diamond** [comment]
Fixed in v. 1.1.13
