### ISSUE TITLE
Resulting chunks not listed in manifest.json

### ISSUE THREAD

**Issue by tingc10** [mike-diamond/media-query-splitting-plugin#4]
I am using `webpack-assets-manifest` to generate a `manifest.json`. Currently, the CSS is splitting out by media query, but the assets are not showing up in my `manifest.json`. How do you recommend loading these assets?

** EDIT **
Also we don't have SSR enabled.

**Comment by mike-diamond** [comment]
I have used assets-webpack-plugin it works well. Please provide an example of your app and I will check it

**Comment by mike-diamond** [comment]
Write me if the problem is still appears

**Comment by stevenmusumeche** [comment]
@mike-diamond I am having the same issue.  The query-based CSS is being generated and removed from the main files, however, they are not being included in `loadable-stats.json`
