### ISSUE TITLE
How can we use this plugin with client side rendering of react app

### ISSUE THREAD

**Issue by jbbpatel94** [mike-diamond/media-query-splitting-plugin#5]

**Comment by mike-diamond** [comment]
Just add it to your webpack config as described in the readme. And ignore the last part about SSR

**Comment by jbbpatel94** [comment]
I added `media-query-splitting-plugin` as devDependencies  in package.json and  webpack.config.js is
```
new MediaQuerySplittingPlugin({
      media: {
        mobileEnd: 568,
        tabletPortraitEnd: 768,
        tabletLandscapeEnd: 1024,
      },
      splitTablet: false,
    })
```

but it's not working.
how browser will figure out which style should load ?

**Comment by mike-diamond** [comment]
You should use it with mini-css-extract-plugin

**Comment by jbbpatel94** [comment]
when I was using in webpack.common.config.js , not working but now i move it in production.config.js its working fine.
