### ISSUE TITLE
Why plugin minimize css

### ISSUE THREAD

**Issue by romanlex** [mike-diamond/media-query-splitting-plugin#7]
When I use this plugin and start build my app I have minimized css files. Why?

**Comment by mike-diamond** [comment]
`clean-css` was included into the plugin, I will add an option to disable it in a couple days.

**Comment by romanlex** [comment]
Thx for option. Are you can unminify source code of project?

**Comment by mike-diamond** [comment]
Implemented in v. 1.1.14 (set `minify: false` in the plugin config to disable css minimize)
