### ISSUE TITLE
Create a demo.html page

### ISSUE THREAD

**Issue by JuanmaMenendez** [mike-diamond/media-query-splitting-plugin#8]
Will be very useful to have a demo.html project and directly see the plugin and his configuration in action.

**Comment by mike-diamond** [comment]
Demo is available in https://github.com/mike-diamond/media-query-splitting-demo
And live version on https://mediaquerysplittingdemo.firebaseapp.com/

**Comment by JuanmaMenendez** [comment]
> Demo is available in https://github.com/mike-diamond/media-query-splitting-demo
> And live version on https://mediaquerysplittingdemo.firebaseapp.com/

The first link is broken. Thanks for the demo!
